/**
 * Sanity content for this site.
 *
 * The site keeps its own codebase and design — only the content comes from
 * Sanity, filtered to this client (`pmm`). That is what lets the daily
 * auto-blog generator publish a post and have it appear here without a deploy.
 *
 * Plain fetch rather than the Sanity SDK: this is a handful of read-only
 * queries and the project already ships small.
 */

const PROJECT_ID = process.env.SANITY_PROJECT_ID || 'ummj0ji2'
const DATASET = process.env.SANITY_DATASET || 'production'
const API = `https://${PROJECT_ID}.api.sanity.io/v2024-01-01`

/** Which client's documents this site renders. */
export const CLIENT_ID = process.env.SANITY_CLIENT_ID || 'pmm'

export interface SanityImageRef {
  _type: 'image'
  asset: { _type: 'reference'; _ref: string }
}

export interface Span {
  _type: 'span'
  _key: string
  text: string
  marks?: string[]
}

export interface PortableBlock {
  _type: string
  _key: string
  style?: string
  listItem?: string
  level?: number
  children: Span[]
  markDefs?: unknown[]
}

export interface BlogPost {
  _id: string
  title: string
  slug: string
  excerpt?: string
  mainImage?: SanityImageRef
  imageAlt?: string
  body?: PortableBlock[]
  publishedAt?: string
  author?: string
  autoGenerated?: boolean
}

export interface LinkItem {
  _key: string
  slug: string
  label: string
}

export interface CheckItem {
  _key: string
  /** Includes its trailing colon — the live pages bold it. */
  label: string
  text: string
}

/** One node of a city page's prose, in document order. */
export interface ContentBlock {
  _type: 'paraBlock' | 'headingBlock' | 'checklistBlock'
  _key: string
  text?: string
  items?: CheckItem[]
}

/** A city or neighbourhood page. Cities have no parentSlug. */
export interface Location {
  _id: string
  name: string
  slug: string
  parentSlug?: string | null
  seoTitle?: string
  seoDescription?: string
  keywords?: string[]
  ogTitle?: string
  ogDescription?: string
  heroHeading?: string
  heroSubheading?: string
  sectionHeading?: string
  content?: ContentBlock[]
  coverageAreas?: string[]
  neighborhoodHeading?: string
  neighborhoodLinks?: LinkItem[]
  ctaHeading?: string
  ctaBody?: string
  nearbyCities?: LinkItem[]
  /* Neighbourhood-only fields */
  cityLabel?: string
  breadcrumbLabel?: string
  bodyParagraphs?: string[]
  landmarksHeading?: string
  landmarks?: string[]
  streetsHeading?: string
  streets?: string[]
  offersHeading?: string
  highlights?: string[]
  backLabel?: string
}

export async function sanityQuery<T>(
  query: string,
  params: Record<string, unknown> = {}
): Promise<T> {
  const url = new URL(`${API}/data/query/${DATASET}`)
  url.searchParams.set('query', query)
  for (const [k, v] of Object.entries(params)) url.searchParams.set(`$${k}`, JSON.stringify(v))

  const res = await fetch(url.toString(), {
    headers: process.env.SANITY_READ_TOKEN
      ? { Authorization: `Bearer ${process.env.SANITY_READ_TOKEN}` }
      : undefined,
    // Pages revalidate on a timer, so a new auto-blog post shows up within a
    // couple of minutes without redeploying.
    next: { revalidate: 120 },
  })
  if (!res.ok) throw new Error(`Sanity query failed (${res.status}): ${(await res.text()).slice(0, 200)}`)
  return (await res.json()).result as T
}

/** CDN URL from an image reference. Ref format: image-{id}-{w}x{h}-{ext} */
export function imageUrl(source: SanityImageRef | null | undefined, width?: number): string | null {
  const ref = source?.asset?._ref
  if (!ref) return null
  const m = ref.match(/^image-([a-f0-9]+)-(\d+x\d+)-(\w+)$/)
  if (!m) return null
  const params = new URLSearchParams({ auto: 'format' })
  if (width) {
    params.set('w', String(width))
    params.set('fit', 'max')
  }
  return `https://cdn.sanity.io/images/${PROJECT_ID}/${DATASET}/${m[1]}-${m[2]}.${m[3]}?${params}`
}

const POST_CARD = `_id, title, "slug": slug.current, excerpt, mainImage, imageAlt, publishedAt, author, autoGenerated`

/**
 * Every post for this client, newest first — hand-written and auto-generated
 * alike. The blog is one stream on purpose: an auto-blog post is a post.
 */
export function getPosts() {
  return sanityQuery<BlogPost[]>(
    `*[_type == "blogPost" && clientId == $c] | order(publishedAt desc) { ${POST_CARD} }`,
    { c: CLIENT_ID }
  )
}

export function getPost(slug: string) {
  return sanityQuery<BlogPost | null>(
    `*[_type == "blogPost" && clientId == $c && slug.current == $slug][0] { ${POST_CARD}, body }`,
    { c: CLIENT_ID, slug }
  )
}

/** Slugs for generateStaticParams. */
export function getPostSlugs() {
  return sanityQuery<string[]>(`*[_type == "blogPost" && clientId == $c].slug.current`, {
    c: CLIENT_ID,
  })
}

const LOCATION_FIELDS = `_id, name, "slug": slug.current, parentSlug, seoTitle, seoDescription,
  keywords, ogTitle, ogDescription, heroHeading, heroSubheading, sectionHeading, content,
  coverageAreas, neighborhoodHeading, neighborhoodLinks, ctaHeading, ctaBody, nearbyCities`

/** A top-level city (no parentSlug). */
export function getCity(slug: string) {
  return sanityQuery<Location | null>(
    `*[_type == "location" && clientId == $c && !defined(parentSlug) && slug.current == $slug][0] { ${LOCATION_FIELDS} }`,
    { c: CLIENT_ID, slug }
  )
}

/** A neighbourhood, identified by its parent city plus its own slug. */
export function getArea(citySlug: string, slug: string) {
  return sanityQuery<Location | null>(
    `*[_type == "location" && clientId == $c && parentSlug == $citySlug && slug.current == $slug][0] {
      ${LOCATION_FIELDS}, cityLabel, breadcrumbLabel, bodyParagraphs, landmarksHeading, landmarks,
      streetsHeading, streets, offersHeading, highlights, backLabel }`,
    { c: CLIENT_ID, citySlug, slug }
  )
}

export function getAreaParams() {
  return sanityQuery<{ city: string; area: string }[]>(
    `*[_type == "location" && clientId == $c && defined(parentSlug)] { "city": parentSlug, "area": slug.current }`,
    { c: CLIENT_ID }
  )
}

export function getCitySlugs() {
  return sanityQuery<string[]>(
    `*[_type == "location" && clientId == $c && !defined(parentSlug)].slug.current`,
    { c: CLIENT_ID }
  )
}

/** Rough read time from the body, the way the hand-built posts stated it. */
export function readingMinutes(body?: PortableBlock[]): number {
  if (!Array.isArray(body)) return 1
  const words = body
    .flatMap((b) => b.children || [])
    .map((c) => c.text || '')
    .join(' ')
    .split(/\s+/)
    .filter(Boolean).length
  return Math.max(1, Math.round(words / 200))
}
