/**
 * Sanity content for this site.
 *
 * The site keeps its own codebase and design — only the content comes from
 * Sanity, filtered to this client (`pmm`). That is what lets the daily
 * auto-blog generator publish a post and have it appear here without a deploy.
 *
 * Plain fetch rather than the Sanity SDK: this is a handful of read-only
 * queries and the project already ships small.
 */

const PROJECT_ID = process.env.SANITY_PROJECT_ID || 'ummj0ji2'
const DATASET = process.env.SANITY_DATASET || 'production'
const API = `https://${PROJECT_ID}.api.sanity.io/v2024-01-01`

/** Which client's documents this site renders. */
export const CLIENT_ID = process.env.SANITY_CLIENT_ID || 'pmm'

export interface SanityImageRef {
  _type: 'image'
  asset: { _type: 'reference'; _ref: string }
}

export interface Span {
  _type: 'span'
  _key: string
  text: string
  marks?: string[]
}

export interface PortableBlock {
  _type: string
  _key: string
  style?: string
  listItem?: string
  level?: number
  children: Span[]
  markDefs?: unknown[]
}

export interface BlogPost {
  _id: string
  title: string
  slug: string
  excerpt?: string
  mainImage?: SanityImageRef
  imageAlt?: string
  body?: PortableBlock[]
  publishedAt?: string
  author?: string
  autoGenerated?: boolean
}

export interface LinkItem {
  _key: string
  slug: string
  label: string
}

export interface CheckItem {
  _key: string
  /** Includes its trailing colon — the live pages bold it. */
  label: string
  text: string
}

/** One node of a city page's prose, in document order. */
export interface ContentBlock {
  _type: 'paraBlock' | 'headingBlock' | 'checklistBlock'
  _key: string
  text?: string
  items?: CheckItem[]
}

/** A city or neighbourhood page. Cities have no parentSlug. */
export interface Location {
  _id: string
  name: string
  slug: string
  parentSlug?: string | null
  seoTitle?: string
  seoDescription?: string
  keywords?: string[]
  ogTitle?: string
  ogDescription?: string
  heroHeading?: string
  heroSubheading?: string
  sectionHeading?: string
  content?: ContentBlock[]
  coverageAreas?: string[]
  neighborhoodHeading?: string
  neighborhoodLinks?: LinkItem[]
  ctaHeading?: string
  ctaBody?: string
  nearbyCities?: LinkItem[]
  /* Neighbourhood-only fields */
  cityLabel?: string
  breadcrumbLabel?: string
  bodyParagraphs?: string[]
  landmarksHeading?: string
  landmarks?: string[]
  streetsHeading?: string
  streets?: string[]
  offersHeading?: string
  highlights?: string[]
  backLabel?: string
}

/* ------------------------------------------------------------------ *
 * Service and page content
 *
 * These documents are shared with the client-site template that renders
 * reviewmonster.com/site/pmm, which reads `title`, `body`, `sections`,
 * `seoTitle` and friends. This site therefore reads its own field names —
 * `metaTitle`, `pageHeading`, `pageSections` — so the two can describe the
 * same page differently without either overwriting the other.
 * ------------------------------------------------------------------ */

/**
 * A run of text, optionally a link. Lets a paragraph carry inline anchors.
 * Distinct from `Span` above, which is portable text's own span type.
 */
export interface TextSpan {
  _key?: string
  text: string
  href?: string
  bold?: boolean
}

/** A list item: an optional bold lead-in ("Family history:") then the rest. */
export interface RichItem {
  _key: string
  label?: string
  spans?: TextSpan[]
  text?: string
}

export interface Callout {
  tone?: 'note' | 'warning'
  icon?: string
  title?: string
  text?: string
}

export interface StepCard {
  _key: string
  title: string
  text?: string
  paras?: string[]
}

/**
 * One block of a service page. `kind` says which of the payload fields is
 * populated — the four service pages genuinely are different shapes, and
 * pretending otherwise is what lost content the first time round.
 */
export interface ServiceSection {
  _key: string
  callout?: Callout
  heading?: string
  kind: 'paras' | 'bullets' | 'checkGrid' | 'stepCards' | 'numberRows'
  paras?: string[]
  bullets?: RichItem[]
  items?: string[]
  steps?: StepCard[]
  /** The one or two sections whose body carried an extra bottom margin. */
  spaced?: boolean
}

export interface ServicePage {
  _id: string
  slug: string
  metaTitle?: string
  metaDescription?: string
  pageHeading?: string
  pageLead?: string
  pageSections?: ServiceSection[]
  pageCtaHeading?: string
  pageCtaBody?: string
  ctaWide?: boolean
}

/** A card in one of the index grids (services, resources, about-us). */
export interface IndexCard {
  _key: string
  title: string
  href: string
  icon?: string
  description?: string
}

const SERVICE_FIELDS = `_id, "slug": slug.current, metaTitle, metaDescription, pageHeading,
  pageLead, pageSections, pageCtaHeading, pageCtaBody, ctaWide`

export function getServicePage(slug: string) {
  return sanityQuery<ServicePage | null>(
    `*[_type == "service" && clientId == $c && slug.current == $slug][0] { ${SERVICE_FIELDS} }`,
    { c: CLIENT_ID, slug }
  )
}

export function getServiceSlugs() {
  return sanityQuery<string[]>(`*[_type == "service" && clientId == $c].slug.current`, {
    c: CLIENT_ID,
  })
}

/** An index page whose body is a grid of cards (services, resources, about-us). */
export interface IndexPage {
  _id: string
  metaTitle?: string
  metaDescription?: string
  pageHeading?: string
  pageLead?: string
  cards?: IndexCard[]
}

/**
 * A long-form content page.
 *
 * Every field is optional and each route reads only the ones it renders. The
 * pages genuinely are different from one another — a shared "blocks" soup
 * would make them editable but unreadable in the CMS, and these are pages the
 * office has to be able to find things in.
 */
export interface ContentPage {
  _id: string
  metaTitle?: string
  metaDescription?: string
  metaKeywords?: string[]
  ogTitle?: string
  ogDescription?: string
  pageHeading?: string
  pageLead?: string
  /** Hero centred rather than left-aligned. */
  centeredHero?: boolean

  cards?: IndexCard[]
  related?: IndexCard[]
  faqs?: { _key: string; question: string; answer: string }[]

  /* cleanup-process */
  steps?: { _key: string; title: string; paras: string[] }[]
  gridHeading?: string
  gridItems?: string[]

  /* hoarding-signs */
  warningSignsHeading?: string
  warningSigns?: { _key: string; title: string; text: string }[]
  compareHeading?: string
  compareIntro?: string
  compare?: { _key: string; tone: 'good' | 'bad'; title: string; items: string[] }[]
  levelsHeading?: string
  levelsIntro?: string
  levels?: { _key: string; label: string; text: string; color: string }[]
  helpHeading?: string
  helpIntro?: string
  helpItems?: string[]
  helpOutro?: string

  /* helping-a-hoarder */
  understandHeading?: string
  understandParas?: string[]
  understandIntro?: string
  understandItems?: string[]
  tipsHeading?: string
  tips?: { _key: string; icon: string; title: string; text: string }[]
  sayTitle?: string
  sayItems?: string[]
  proHeading?: string
  proIntro?: string
  proItems?: RichItem[]
  proOutro?: string
  selfHeading?: string
  selfIntro?: string
  selfItems?: string[]

  /* about-us */
  approachHeading?: string
  approachParas?: string[]
  reasons?: { _key: string; title: string; text: string }[]
  goodHeading?: string
  goodIntro?: string
  goodItems?: RichItem[]
  goodOutro?: string
  quickFacts?: { _key: string; icon: string; title: string; text: string }[]
  richBlocks?: RichBlock[]
  linksTitle?: string
  links?: { _key: string; text: string; href: string }[]

  /* testimonials */
  rating?: number
  totalReviews?: number
  reviewsIntro?: string
  reviews?: { _key: string; author: string; rating: number; when: string; text: string }[]
  outroPrefix?: string
  outroBold?: string
  outroSuffix?: string
  outroSecond?: string
  bookHeading?: string

  pageCtaHeading?: string
  pageCtaBody?: string
  ctaWide?: boolean
}

/** Prose that carries inline links, which a plain string cannot. */
export interface RichBlock {
  _key: string
  type: 'h2' | 'p' | 'ul' | 'ol'
  text?: string
  spans?: TextSpan[]
  items?: RichItem[]
}

export function getContentPage(slug: string) {
  return sanityQuery<ContentPage | null>(
    `*[_type == "page" && clientId == $c && slug.current == $slug][0]`,
    { c: CLIENT_ID, slug }
  )
}

export function getIndexPage(slug: string) {
  return sanityQuery<IndexPage | null>(
    `*[_type == "page" && clientId == $c && slug.current == $slug][0] {
      _id, metaTitle, metaDescription, pageHeading, pageLead, cards }`,
    { c: CLIENT_ID, slug }
  )
}

export async function sanityQuery<T>(
  query: string,
  params: Record<string, unknown> = {}
): Promise<T> {
  const url = new URL(`${API}/data/query/${DATASET}`)
  url.searchParams.set('query', query)
  for (const [k, v] of Object.entries(params)) url.searchParams.set(`$${k}`, JSON.stringify(v))

  const res = await fetch(url.toString(), {
    headers: process.env.SANITY_READ_TOKEN
      ? { Authorization: `Bearer ${process.env.SANITY_READ_TOKEN}` }
      : undefined,
    // Pages revalidate on a timer, so a new auto-blog post shows up within a
    // couple of minutes without redeploying.
    next: { revalidate: 120 },
  })
  if (!res.ok) throw new Error(`Sanity query failed (${res.status}): ${(await res.text()).slice(0, 200)}`)
  return (await res.json()).result as T
}

/** CDN URL from an image reference. Ref format: image-{id}-{w}x{h}-{ext} */
export function imageUrl(source: SanityImageRef | null | undefined, width?: number): string | null {
  const ref = source?.asset?._ref
  if (!ref) return null
  const m = ref.match(/^image-([a-f0-9]+)-(\d+x\d+)-(\w+)$/)
  if (!m) return null
  const params = new URLSearchParams({ auto: 'format' })
  if (width) {
    params.set('w', String(width))
    params.set('fit', 'max')
  }
  return `https://cdn.sanity.io/images/${PROJECT_ID}/${DATASET}/${m[1]}-${m[2]}.${m[3]}?${params}`
}

const POST_CARD = `_id, title, "slug": slug.current, excerpt, mainImage, imageAlt, publishedAt, author, autoGenerated`

/**
 * Every post for this client, newest first — hand-written and auto-generated
 * alike. The blog is one stream on purpose: an auto-blog post is a post.
 */
export function getPosts() {
  return sanityQuery<BlogPost[]>(
    `*[_type == "blogPost" && clientId == $c] | order(publishedAt desc) { ${POST_CARD} }`,
    { c: CLIENT_ID }
  )
}

export function getPost(slug: string) {
  return sanityQuery<BlogPost | null>(
    `*[_type == "blogPost" && clientId == $c && slug.current == $slug][0] { ${POST_CARD}, body }`,
    { c: CLIENT_ID, slug }
  )
}

/** Slugs for generateStaticParams. */
export function getPostSlugs() {
  return sanityQuery<string[]>(`*[_type == "blogPost" && clientId == $c].slug.current`, {
    c: CLIENT_ID,
  })
}

const LOCATION_FIELDS = `_id, name, "slug": slug.current, parentSlug, seoTitle, seoDescription,
  keywords, ogTitle, ogDescription, heroHeading, heroSubheading, sectionHeading, content,
  coverageAreas, neighborhoodHeading, neighborhoodLinks, ctaHeading, ctaBody, nearbyCities`

/** A top-level city (no parentSlug). */
export function getCity(slug: string) {
  return sanityQuery<Location | null>(
    `*[_type == "location" && clientId == $c && !defined(parentSlug) && slug.current == $slug][0] { ${LOCATION_FIELDS} }`,
    { c: CLIENT_ID, slug }
  )
}

/** A neighbourhood, identified by its parent city plus its own slug. */
export function getArea(citySlug: string, slug: string) {
  return sanityQuery<Location | null>(
    `*[_type == "location" && clientId == $c && parentSlug == $citySlug && slug.current == $slug][0] {
      ${LOCATION_FIELDS}, cityLabel, breadcrumbLabel, bodyParagraphs, landmarksHeading, landmarks,
      streetsHeading, streets, offersHeading, highlights, backLabel }`,
    { c: CLIENT_ID, citySlug, slug }
  )
}

export function getAreaParams() {
  return sanityQuery<{ city: string; area: string }[]>(
    `*[_type == "location" && clientId == $c && defined(parentSlug)] { "city": parentSlug, "area": slug.current }`,
    { c: CLIENT_ID }
  )
}

export function getCitySlugs() {
  return sanityQuery<string[]>(
    `*[_type == "location" && clientId == $c && !defined(parentSlug)].slug.current`,
    { c: CLIENT_ID }
  )
}

/** Rough read time from the body, the way the hand-built posts stated it. */
export function readingMinutes(body?: PortableBlock[]): number {
  if (!Array.isArray(body)) return 1
  const words = body
    .flatMap((b) => b.children || [])
    .map((c) => c.text || '')
    .join(' ')
    .split(/\s+/)
    .filter(Boolean).length
  return Math.max(1, Math.round(words / 200))
}
